name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject API keys
        run: |
          sed -i "s/\"DEEPSEEK_API_KEY\"/\"${{ secrets.DEEPSEEK_API_KEY }}\"/g" index.html
          sed -i "s/\"RAPIDAPI_KEY\"/\"${{ secrets.RAPIDAPI_KEY }}\"/g" index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
